### ISSUE TITLE
the openvpn addon gives me this error (errno=22)

### ISSUE THREAD

**Issue by RssFra97** [rbray89/hassio-addons#5]
Good morning,
after updating Home Assistant gives me this error: Sun Mar  3 15:19:37 2019 Failed to truncate status file: Invalid argument (errno=22), how do I solve?

**Comment by RWGaMeR** [comment]
@rbray89 anything?

**Comment by RWGaMeR** [comment]
OpenVPN CLIENT LIST
Updated,Mon Mar  4 14:04:39 2019
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
GLOBAL STATS
Max bcast/mcast queue length,0
END
Mon Mar  4 14:04:39 2019 Failed to truncate status file: Invalid argument (errno=22)

**Comment by rbray89** [comment]
It was working previously? Did you try restarting the addon? Looks like it either is a diskspace issue or file lock due to the status log file. 

Is this killing the addon or simply a warning message? I found an OpenVPN thread that describes this issue indicating that it is likely a warning, and should not be affecting things: https://forums.openvpn.net/viewtopic.php?t=18885

If you have already tried restarting the addon, you could try rebuilding the addon to see if that clears the file.

**Comment by RWGaMeR** [comment]
@rbray89  
the problem is that it does not connect and tells me that I have problems with ddns, the addon I have uninstalled and reinstalled, but nothing always usually wrong

**Comment by rbray89** [comment]
What entity is telling you you have problems with DNS? (Client, server?) You have the logs for that?

**Comment by rbray89** [comment]
Note that DNS on the same host may not be supported without some work: 
https://github.com/rbray89/hassio-addons/issues/4

**Comment by RWGaMeR** [comment]
> What entity is telling you you have problems with DNS? (Client, server?) You have the logs for that?

the message tells me the client at the connection

**Comment by RWGaMeR** [comment]
@rbray89 
this is a log https://pastebin.com/bhU2FyA8

**Comment by rbray89** [comment]
Looks like your openVPN client may not have all the necessary permissions:

> Error in add_block_dns_filters(): add_sublayer: failed to add persistent sublayer : Accesso negato. 

Have you also tried using only non-local DNS addresses (1.1.1.1, 8.8.8.8)?

This doesn't seem to be an issue with this addon though, seems to be a client setup issue.

**Comment by RWGaMeR** [comment]
@rbray89 ok, I try to restart the client

**Comment by RWGaMeR** [comment]
@rbray89 thanks, reboot client worked

**Comment by RWGaMeR** [comment]
I have resolve block dns, I have deleting this is string: setenv opt block-outside-dns # Prevent Windows 10 DNS leak
